language: php
php:
  - "5.5"
  - "5.6"
before_script:
  - mysql -e 'create database homestead;'
  - "composer self-update"
  - "composer install --dev --no-interaction"
script:
  - mkdir -p build/logs
  - phpunit
#  - phpunit --coverage-clover build/logs/clover.xml
#after_script:
# - vendor/bin/coveralls -v